version: '3.8'

services:
  db:
    image: mysql:8.0.23
    container_name: ch-db
    restart: always
    ports:
      - 3306:3306
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=ChatRoom
    networks:
      - ch-network

  backend:
    container_name: ch-back
    build: 
      context: ./backend
      dockerfile: dockerfile
    depends_on:
      - db
    working_dir: /app
    restart: on-failure
    tty: true
    stdin_open: true
    ports:
      - 3001:3001
    volumes:
      - ./backend:/app
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_HOST=db
      - MYSQL_DATABASE=ChatRoom
    networks:
      - ch-network

  frontend:
    build: ./frontend
    container_name: ch-front
    working_dir: /app
    restart: on-failure
    tty: true
    stdin_open: true
    environment:
      - API_HOST=back
      - API_PORT=3001
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

networks:
  ch-network:
    driver: bridge     